const swaggerJsdoc = require("swagger-jsdoc");

const options = {
  definition: {
    openapi: "3.0.0",
    info: {
      title: "WDP Manga API",
      version: "1.0.0",
      description: "Webcomic Distribution Platform — Manga Management API",
    },
    servers: [
      {
        url: "https://wdp-be-a2qb.onrender.com",
        description: "Production server",
      },
    ],
    components: {
      securitySchemes: {
        BearerAuth: {
          type: "http",
          scheme: "bearer",
          bearerFormat: "JWT",
        },
      },
      schemas: {
        Series: {
          type: "object",
          properties: {
            _id: { type: "string" },
            name: { type: "string" },
            description: { type: "string" },
            genre: { type: "string" },
            target_audience: { type: "string" },
            synopsis: { type: "string" },
            author_id: { type: "string" },
            status: { type: "string", enum: ["draft", "submitted", "approved", "rejected", "published", "cancelled"] },
            publication_schedule: { type: "string", enum: ["weekly", "monthly", "null"] },
            is_public: { type: "boolean" },
            average_score: { type: "number" },
            total_votes: { type: "integer" },
            views_count: { type: "integer" },
            cover_image_url: { type: "string" },
            tags: { type: "array", items: { type: "string" } },
            age_rating: { type: "string", enum: ["All ages", "Teens 13+", "Mature 17+", "Adults Only 18+"] },
            eb_evaluation_id: { type: "string", nullable: true },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        Chapter: {
          type: "object",
          properties: {
            _id: { type: "string" },
            series_id: { type: "string" },
            chapter_number: { type: "integer" },
            title: { type: "string" },
            status: { type: "string", enum: ["draft", "pending_assistant", "submitted_by_assistant", "pending_TE", "TE_revision", "pending_EB", "EB_revision", "approved_by_EB", "published", "review", "revision_requested"] },
            submitted_by: { type: "string" },
            te_review_id: { type: "string", nullable: true },
            eb_evaluation_id: { type: "string", nullable: true },
            assistant_id: {
              type: "string",
              nullable: true,
              description: "User ID của Assistant gắn với chapter. Phải có Cooperation đã accepted với Mangaka cho series này (hoặc cooperation chung series_id=null). Sau khi chapter có PurchasedChapter đầu tiên, không thể thay đổi assistant_id.",
            },
            revision_notes: { type: "string" },
            revision_annotations: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  page_id: { type: "string" },
                  region: {
                    type: "object",
                    properties: {
                      x: { type: "number" },
                      y: { type: "number" },
                      width: { type: "number" },
                      height: { type: "number" },
                    },
                  },
                  content: { type: "string" },
                  error_type: { type: "string", enum: ["content", "dialogue", "script", "art", "other"] },
                },
              },
            },
            revision_source: { type: "string", enum: ["TE", "EB", "Mangaka", ""] },
            is_published: { type: "boolean" },
            published_at: { type: "string", format: "date-time", nullable: true },
            views_count: { type: "integer" },
            cover_image_url: { type: "string" },
            access_type: { type: "string", enum: ["FREE", "PAID"], default: "PAID", description: "FREE cho chapter 1 (cứng). Chapter 2+ mặc định PAID, có thể override FREE." },
            coin_price: { type: "number", default: 5, description: "CỐ ĐỊNH = 5 Coin cho chapter PAID. Chapter 1 = 0." },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        Task: {
          type: "object",
          properties: {
            _id: { type: "string" },
            page_id: { type: "string" },
            chapter_id: { type: "string" },
            assigned_by: { type: "string" },
            assigned_to: { type: "string" },
            work_type: { type: "string", enum: ["background", "shading", "effects", "details", "other"] },
            region: {
              type: "object",
              properties: { x: { type: "number" }, y: { type: "number" }, width: { type: "number" }, height: { type: "number" } },
            },
            description: { type: "string" },
            revision_note: { type: "string" },
            status: { type: "string", enum: ["pending", "in_progress", "submitted", "approved", "revision", "archived"] },
            round: { type: "integer", description: "Vòng sửa (1 = lần đầu, 2+ = revision)" },
            is_current_round: { type: "boolean" },
            result_image_url: { type: "string" },
            note_ids: {
              type: "array",
              description: "Danh sách PageNote liên kết (khi populate trả về object có text, x, y, w, h, taskType, note_kind, author_role, revision_round)",
              items: { $ref: "#/components/schemas/PageNote" },
            },
            price: { type: "number" },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        PageNote: {
          type: "object",
          description: "Ghi chú của Mangaka trên page (dùng cho brief & revision)",
          properties: {
            _id: { type: "string" },
            page_id: { type: "string" },
            author_id: { type: "string" },
            text: { type: "string" },
            x: { type: "number", minimum: 0, maximum: 100, description: "Tọa độ X (%)" },
            y: { type: "number", minimum: 0, maximum: 100, description: "Tọa độ Y (%)" },
            w: { type: "number", minimum: 0, maximum: 100, description: "Chiều rộng vùng (%)" },
            h: { type: "number", minimum: 0, maximum: 100, description: "Chiều cao vùng (%)" },
            taskType: { type: "string", enum: ["background", "shading", "fx", "other"] },
            note_kind: { type: "string", enum: ["brief", "revision"], description: "brief = gửi lần đầu, revision = yêu cầu sửa" },
            author_role: { type: "string", enum: ["mangaka", "assistant", "te", "eb"], default: "mangaka" },
            revision_round: { type: "integer", default: 1 },
            status: { type: "string", enum: ["active", "used_in_task"], default: "active" },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        Vote: {
          type: "object",
          properties: {
            _id: { type: "string" },
            series_id: { type: "string" },
            reader_id: { type: "string" },
            score: { type: "integer", minimum: 1, maximum: 10 },
            comment: { type: "string" },
            release_period: { type: "string" },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        TEReview: {
          type: "object",
          properties: {
            _id: { type: "string" },
            chapter_id: { type: "string" },
            reviewed_by: { type: "string" },
            decision: { type: "string", enum: ["draft", "revision", "approved", "rejected", "approved_publish"] },
            annotations: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  _id: { type: "string" },
                  page_id: { type: "string" },
                  region: { type: "object", properties: { x: { type: "number" }, y: { type: "number" }, width: { type: "number" }, height: { type: "number" } } },
                  content: { type: "string" },
                  error_type: { type: "string", enum: ["content", "dialogue", "script", "art", "other"] },
                },
              },
            },
            feedback: { type: "string" },
            revision_feedback: { type: "string" },
            quick_notes: { type: "string" },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        EBEvaluation: {
          type: "object",
          properties: {
            _id: { type: "string" },
            series_id: { type: "string" },
            chapter_id: { type: "string", nullable: true },
            evaluated_by: { type: "string" },
            story_type: { type: "string" },
            preview_images: { type: "array", items: { type: "string" } },
            status: { type: "string", enum: ["scoring", "saved", "locked"] },
            first_review: { type: "boolean" },
            member_scores: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  member_name: { type: "string" },
                  member_id: { type: "string", nullable: true },
                  scores: {
                    type: "object",
                    properties: {
                      story_dialogue: { type: "number" },
                      art_design: { type: "number" },
                      panel_camera: { type: "number" },
                      pacing_climax: { type: "number" },
                      color: { type: "number" },
                    },
                  },
                  comments: {
                    type: "object",
                    properties: {
                      story_dialogue: { type: "string" },
                      art_design: { type: "string" },
                      panel_camera: { type: "string" },
                      pacing_climax: { type: "string" },
                      color: { type: "string" },
                    },
                  },
                  overall_comment: { type: "string" },
                  average: { type: "number" },
                  total_score: { type: "number" },
                  saved_at: { type: "string", format: "date-time" },
                  notes: { type: "string" },
                },
              },
            },
            quick_decision: { type: "string", enum: ["approved", "rejected", "revision", "null"] },
            quick_notes: { type: "string" },
            result: { type: "string", enum: ["approved", "rejected", "revision", "null"] },
            publication_schedule: { type: "string", enum: ["weekly", "monthly", "null"] },
            notes: { type: "string" },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        EBScoreSummary: {
          type: "object",
          properties: {
            chapter_id: { type: "string" },
            series_id: { type: "string" },
            series_name: { type: "string" },
            evaluation_id: { type: "string", nullable: true },
            evaluation_status: { type: "string", enum: ["scoring", "saved", "locked"] },
            story_type: { type: "string" },
            member_stats: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  member_name: { type: "string" },
                  scores: {
                    type: "object",
                    properties: {
                      story_dialogue: { type: "number" },
                      art_design: { type: "number" },
                      panel_camera: { type: "number" },
                      pacing_climax: { type: "number" },
                      color: { type: "number" },
                    },
                  },
                  average: { type: "number" },
                  overall_comment: { type: "string" },
                  saved_at: { type: "string", format: "date-time" },
                },
              },
            },
            aggregate: {
              type: "object",
              nullable: true,
              properties: {
                scores_per_criteria: {
                  type: "object",
                  properties: {
                    story_dialogue: { type: "number" },
                    art_design: { type: "number" },
                    panel_camera: { type: "number" },
                    pacing_climax: { type: "number" },
                    color: { type: "number" },
                  },
                },
                council_average: { type: "number" },
                total_score: { type: "number" },
                label_code: { type: "string", enum: ["khong_dat", "dat", "tot", "xuat_sac"] },
                label_text: { type: "string", enum: ["Không đạt", "Đạt", "Tốt", "Xuất sắc"] },
                member_count: { type: "integer" },
              },
            },
            criteria_labels: {
              type: "object",
              additionalProperties: { type: "string" },
            },
          },
        },
        Notification: {
          type: "object",
          properties: {
            _id: { type: "string" },
            user_id: { type: "string" },
            type: { type: "string" },
            title: { type: "string" },
            message: { type: "string" },
            is_read: { type: "boolean" },
            related_entity_type: { type: "string", enum: ["series", "chapter", "page", "task", "cooperation_request", "cooperation", "te_review", "eb_evaluation", "vote"] },
            related_entity_id: { type: "string", nullable: true },
            meta: { type: "object", additionalProperties: true },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        CoinPackage: {
          type: "object",
          properties: {
            _id: { type: "string" },
            name: { type: "string" },
            description: { type: "string" },
            price_vnd: { type: "number" },
            coin_amount: { type: "number" },
            bonus_coin: { type: "number" },
            total_coin: { type: "number" },
            sort_order: { type: "integer" },
            is_active: { type: "boolean" },
          },
        },
        Payment: {
          type: "object",
          properties: {
            _id: { type: "string" },
            user_id: { type: "string" },
            coin_package_id: { type: "string" },
            order_code: { type: "number" },
            amount_vnd: { type: "number" },
            coin_amount: { type: "number" },
            status: { type: "string", enum: ["pending", "paid", "cancelled", "expired", "failed"] },
            description: { type: "string" },
            checkout_url: { type: "string" },
            paid_at: { type: "string", format: "date-time", nullable: true },
            createdAt: { type: "string", format: "date-time" },
          },
        },
        Wallet: {
          type: "object",
          properties: {
            _id: { type: "string" },
            user_id: { type: "string" },
            balance: { type: "number" },
            total_deposited: { type: "number" },
            total_spent: { type: "number" },
            pending_balance: { type: "number" },
            available_balance: { type: "number" },
            total_revenue: { type: "number" },
            total_withdrawn: { type: "number" },
          },
        },
        WalletTransaction: {
          type: "object",
          properties: {
            _id: { type: "string" },
            wallet_id: { type: "string" },
            user_id: { type: "string" },
            type: { type: "string", enum: ["Deposit", "Purchase", "Revenue", "Withdrawal", "Refund"] },
            direction: { type: "string", enum: ["in", "out"] },
            coin_amount: { type: "number" },
            vnd_amount: { type: "number" },
            description: { type: "string" },
            chapter_id: { type: "string", nullable: true },
            payment_id: { type: "string", nullable: true },
            revenue_id: { type: "string", nullable: true },
            withdrawal_id: { type: "string", nullable: true },
            createdAt: { type: "string", format: "date-time" },
          },
        },
        PurchasedChapter: {
          type: "object",
          properties: {
            _id: { type: "string" },
            reader_id: { type: "string" },
            chapter_id: { type: "string" },
            series_id: { type: "string" },
            price: { type: "number" },
            purchased_at: { type: "string", format: "date-time" },
          },
        },
        Revenue: {
          type: "object",
          description: "Revenue share được xác định từ chapter.assistant_id, không còn lấy từ Cooperation.revenue_shares. Trường cooperation_snapshot chỉ phục vụ audit.",
          properties: {
            _id: { type: "string" },
            user_id: { type: "string" },
            user_role: { type: "string", enum: ["Mangaka", "Assistant"] },
            series_id: { type: "string" },
            chapter_id: { type: "string" },
            reader_id: { type: "string" },
            gross_coin_amount: { type: "number" },
            platform_fee_coin: { type: "number" },
            net_coin_amount: { type: "number" },
            share_percentage: { type: "number", description: "100% nếu chapter không có assistant. 60% (Mangaka) hoặc 40% (Assistant) nếu có assistant." },
            coin_amount: { type: "number" },
            vnd_amount: { type: "number" },
            status: { type: "string", enum: ["pending", "available", "withdrawn"] },
            available_at: { type: "string", format: "date-time" },
            available_at_processed_at: { type: "string", format: "date-time", nullable: true },
            cooperation_snapshot: {
              type: "object",
              description: "Snapshot revenue rule. source = CHAPTER_ASSISTANT (mới) | COOPERATION (cũ, deprecated).",
              properties: {
                source: { type: "string", enum: ["CHAPTER_ASSISTANT", "COOPERATION", null] },
                mangaka_id: { type: "string" },
                assistant_id: { type: "string", nullable: true },
                shares: { type: "array", items: { type: "object" } },
                platform_fee_percentage: { type: "number" },
              },
            },
            createdAt: { type: "string", format: "date-time" },
          },
        },
        Withdrawal: {
          type: "object",
          properties: {
            _id: { type: "string" },
            user_id: { type: "string" },
            user_role: { type: "string", enum: ["Mangaka", "Assistant"] },
            coin_amount: { type: "number" },
            vnd_amount: { type: "number" },
            status: { type: "string", enum: ["pending", "approved", "completed", "rejected", "cancelled"] },
            bank_snapshot: {
              type: "object",
              properties: {
                bank_name: { type: "string" },
                account_holder: { type: "string" },
                account_number: { type: "string" },
                account_number_masked: { type: "string" },
              },
            },
            note: { type: "string" },
            admin_note: { type: "string" },
            createdAt: { type: "string", format: "date-time" },
          },
        },
        FinancialSummary: {
          type: "object",
          description: "Tổng hợp nhanh toàn bộ số liệu tài chính của 1 user (cho cả Reader và Mangaka/Assistant)",
          properties: {
            current_coin: { type: "number", description: "Số Coin hiện có thể dùng mua chapter (Reader.balance)" },
            current_balance: { type: "number", description: "Alias của current_coin — cho frontend dễ đọc" },
            pending_revenue: { type: "number", description: "Coin đang ở trạng thái pending (chỉ Mangaka/Assistant)" },
            available_balance: { type: "number", description: "Coin đã available, có thể yêu cầu withdrawal (chỉ Mangaka/Assistant)" },
            total_deposit: { type: "number", description: "Tổng Coin đã nạp qua PayOS" },
            total_purchase: { type: "number", description: "Tổng Coin đã dùng mua chapter" },
            total_revenue: { type: "number", description: "Tổng doanh thu chia (chỉ Mangaka/Assistant)" },
            total_withdrawal: { type: "number", description: "Tổng Coin đã yêu cầu rút (chỉ Mangaka/Assistant)" },
            total_refund: { type: "number", description: "Tổng Coin được hoàn lại" },
          },
        },
        RevenueBySeries: {
          type: "object",
          properties: {
            series_id: { type: "string" },
            series_name: { type: "string" },
            cover_image_url: { type: "string" },
            total_coin: { type: "number" },
            total_vnd: { type: "number" },
            total_gross_coin: { type: "number" },
            total_platform_fee_coin: { type: "number" },
            chapters_sold: { type: "integer" },
            by_status: {
              type: "object",
              properties: {
                pending_coin: { type: "number" },
                available_coin: { type: "number" },
                withdrawn_coin: { type: "number" },
              },
            },
          },
        },
        CooperationRevenueShare: {
          type: "object",
          properties: {
            cooperation_id: { type: "string" },
            mangaka: {
              type: "object",
              properties: {
                _id: { type: "string" },
                username: { type: "string" },
                full_name: { type: "string" },
              },
            },
            assistant: {
              type: "object",
              properties: {
                _id: { type: "string" },
                username: { type: "string" },
                full_name: { type: "string" },
              },
            },
            series: {
              type: "object",
              nullable: true,
              description: "null = áp dụng cho tất cả series của Mangaka",
              properties: {
                _id: { type: "string" },
                name: { type: "string" },
              },
            },
            revenue_shares: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  user_id: { type: "string" },
                  role: { type: "string", enum: ["Mangaka", "Assistant"] },
                  percentage: { type: "number" },
                },
              },
            },
            agreed_at: { type: "string", format: "date-time" },
          },
        },
        TopEarnerEntry: {
          type: "object",
          properties: {
            user_id: { type: "string" },
            username: { type: "string" },
            full_name: { type: "string" },
            avatar_url: { type: "string" },
            role: { type: "string", enum: ["Mangaka", "Assistant", "Reader"] },
            total_coin: { type: "number" },
            total_vnd: { type: "number" },
            total_gross_coin: { type: "number" },
            total_platform_fee_coin: { type: "number" },
            chapters_sold: { type: "integer" },
            withdrawn_coin: { type: "number" },
          },
        },
        TopReaderEntry: {
          type: "object",
          properties: {
            user_id: { type: "string" },
            username: { type: "string" },
            full_name: { type: "string" },
            avatar_url: { type: "string" },
            role: { type: "string", enum: ["Reader"] },
            total_coin_spent: { type: "number" },
            chapters_bought: { type: "integer" },
          },
        },
        TopSeriesEntry: {
          type: "object",
          properties: {
            series_id: { type: "string" },
            series_name: { type: "string" },
            cover_image_url: { type: "string" },
            author: {
              type: "object",
              nullable: true,
              properties: {
                _id: { type: "string" },
                username: { type: "string" },
                full_name: { type: "string" },
              },
            },
            chapters_sold: { type: "integer" },
            total_coin: { type: "number" },
            total_platform_fee_coin: { type: "number" },
            total_platform_fee_vnd: { type: "number" },
            total_gross_coin: { type: "number" },
          },
        },
      },
    },
    security: [{ BearerAuth: [] }],
  },
  apis: ["./routes/*.js"],
};

const swaggerSpec = swaggerJsdoc(options);
module.exports = swaggerSpec;
