const swaggerJsdoc = require("swagger-jsdoc");

const options = {
  definition: {
    openapi: "3.0.0",
    info: {
      title: "WDP Manga API",
      version: "1.0.0",
      description: "Webcomic Distribution Platform — Manga Management API. Monetary Coin fields are integer CoinUnit values: 100 CoinUnit = 1 Coin. Display fields are strings and must not be used for financial calculations.",
    },
    servers: [
      {
        url: "https://wdp-be-a2qb.onrender.com",
        description: "Production server",
      },
    ],
    components: {
      securitySchemes: {
        BearerAuth: {
          type: "http",
          scheme: "bearer",
          bearerFormat: "JWT",
        },
      },
      schemas: {
        Series: {
          type: "object",
          properties: {
            _id: { type: "string" },
            name: { type: "string" },
            description: { type: "string" },
            genre: { type: "string" },
            target_audience: { type: "string" },
            synopsis: { type: "string" },
            author_id: { type: "string" },
            status: { type: "string", enum: ["draft", "submitted", "approved", "rejected", "published", "cancelled"] },
            publication_schedule: { type: "string", enum: ["weekly", "monthly", "null"] },
            is_public: { type: "boolean" },
            average_score: { type: "number" },
            total_votes: { type: "integer" },
            views_count: { type: "integer" },
            cover_image_url: { type: "string" },
            tags: { type: "array", items: { type: "string" } },
            age_rating: { type: "string", enum: ["All ages", "Teens 13+", "Mature 17+", "Adults Only 18+"] },
            eb_evaluation_id: { type: "string", nullable: true },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        Chapter: {
          type: "object",
          properties: {
            _id: { type: "string" },
            series_id: { type: "string" },
            chapter_number: { type: "integer" },
            title: { type: "string" },
            status: { type: "string", enum: ["draft", "pending_assistant", "submitted_by_assistant", "pending_TE", "TE_revision", "pending_EB", "EB_revision", "approved_by_EB", "published", "review", "revision_requested"] },
            submitted_by: { type: "string" },
            te_review_id: { type: "string", nullable: true },
            eb_evaluation_id: { type: "string", nullable: true },
            assistant_id: {
              type: "string",
              nullable: true,
              description: "User ID của Assistant gắn với chapter. Phải có Cooperation đã accepted với Mangaka cho series này (hoặc cooperation chung series_id=null). Sau khi chapter có PurchasedChapter đầu tiên, không thể thay đổi assistant_id.",
            },
            revision_notes: { type: "string" },
            revision_annotations: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  page_id: { type: "string" },
                  region: {
                    type: "object",
                    properties: {
                      x: { type: "number" },
                      y: { type: "number" },
                      width: { type: "number" },
                      height: { type: "number" },
                    },
                  },
                  content: { type: "string" },
                  error_type: { type: "string", enum: ["content", "dialogue", "script", "art", "other"] },
                },
              },
            },
            revision_source: { type: "string", enum: ["TE", "EB", "Mangaka", ""] },
            is_published: { type: "boolean" },
            published_at: { type: "string", format: "date-time", nullable: true },
            views_count: { type: "integer" },
            cover_image_url: { type: "string" },
            access_type: { type: "string", enum: ["FREE", "PAID"], default: "PAID", description: "FREE cho chapter 1 (cứng). Chapter 2+ mặc định PAID, có thể override FREE." },
            coin_price: { type: "integer", format: "int64", default: 500, description: "Raw CoinUnit. CỐ ĐỊNH 500 CoinUnit = 5.00 Coin cho chapter PAID; chapter 1 = 0." },
            coin_price_coin: { type: "string", example: "5.00" },
            coin_unit_scale: { type: "integer", example: 100 },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        Task: {
          type: "object",
          properties: {
            _id: { type: "string" },
            page_id: { type: "string" },
            chapter_id: { type: "string" },
            assigned_by: { type: "string" },
            assigned_to: { type: "string" },
            work_type: { type: "string", enum: ["background", "shading", "effects", "details", "other"] },
            region: {
              type: "object",
              properties: { x: { type: "number" }, y: { type: "number" }, width: { type: "number" }, height: { type: "number" } },
            },
            description: { type: "string" },
            revision_note: { type: "string" },
            status: { type: "string", enum: ["pending", "in_progress", "submitted", "approved", "revision", "archived"] },
            round: { type: "integer", description: "Vòng sửa (1 = lần đầu, 2+ = revision)" },
            is_current_round: { type: "boolean" },
            result_image_url: { type: "string" },
            note_ids: {
              type: "array",
              description: "Danh sách PageNote liên kết (khi populate trả về object có text, x, y, w, h, taskType, note_kind, author_role, revision_round)",
              items: { $ref: "#/components/schemas/PageNote" },
            },
            price: { type: "number" },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        PageNote: {
          type: "object",
          description: "Ghi chú của Mangaka trên page (dùng cho brief & revision)",
          properties: {
            _id: { type: "string" },
            page_id: { type: "string" },
            author_id: { type: "string" },
            text: { type: "string" },
            x: { type: "number", minimum: 0, maximum: 100, description: "Tọa độ X (%)" },
            y: { type: "number", minimum: 0, maximum: 100, description: "Tọa độ Y (%)" },
            w: { type: "number", minimum: 0, maximum: 100, description: "Chiều rộng vùng (%)" },
            h: { type: "number", minimum: 0, maximum: 100, description: "Chiều cao vùng (%)" },
            taskType: { type: "string", enum: ["background", "shading", "fx", "other"] },
            note_kind: { type: "string", enum: ["brief", "revision"], description: "brief = gửi lần đầu, revision = yêu cầu sửa" },
            author_role: { type: "string", enum: ["mangaka", "assistant", "te", "eb"], default: "mangaka" },
            revision_round: { type: "integer", default: 1 },
            status: { type: "string", enum: ["active", "used_in_task"], default: "active" },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        Vote: {
          type: "object",
          properties: {
            _id: { type: "string" },
            series_id: { type: "string" },
            reader_id: { type: "string" },
            score: { type: "integer", minimum: 1, maximum: 10 },
            comment: { type: "string" },
            release_period: { type: "string" },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        TEReview: {
          type: "object",
          properties: {
            _id: { type: "string" },
            chapter_id: { type: "string" },
            reviewed_by: { type: "string" },
            decision: { type: "string", enum: ["draft", "revision", "approved", "rejected", "approved_publish"] },
            annotations: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  _id: { type: "string" },
                  page_id: { type: "string" },
                  region: { type: "object", properties: { x: { type: "number" }, y: { type: "number" }, width: { type: "number" }, height: { type: "number" } } },
                  content: { type: "string" },
                  error_type: { type: "string", enum: ["content", "dialogue", "script", "art", "other"] },
                },
              },
            },
            feedback: { type: "string" },
            revision_feedback: { type: "string" },
            quick_notes: { type: "string" },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        EBEvaluation: {
          type: "object",
          properties: {
            _id: { type: "string" },
            series_id: { type: "string" },
            chapter_id: { type: "string", nullable: true },
            evaluated_by: { type: "string" },
            story_type: { type: "string" },
            preview_images: { type: "array", items: { type: "string" } },
            status: { type: "string", enum: ["scoring", "saved", "locked"] },
            first_review: { type: "boolean" },
            member_scores: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  member_name: { type: "string" },
                  member_id: { type: "string", nullable: true },
                  scores: {
                    type: "object",
                    properties: {
                      story_dialogue: { type: "number" },
                      art_design: { type: "number" },
                      panel_camera: { type: "number" },
                      pacing_climax: { type: "number" },
                      color: { type: "number" },
                    },
                  },
                  comments: {
                    type: "object",
                    properties: {
                      story_dialogue: { type: "string" },
                      art_design: { type: "string" },
                      panel_camera: { type: "string" },
                      pacing_climax: { type: "string" },
                      color: { type: "string" },
                    },
                  },
                  overall_comment: { type: "string" },
                  average: { type: "number" },
                  total_score: { type: "number" },
                  saved_at: { type: "string", format: "date-time" },
                  notes: { type: "string" },
                },
              },
            },
            quick_decision: { type: "string", enum: ["approved", "rejected", "revision", "null"] },
            quick_notes: { type: "string" },
            result: { type: "string", enum: ["approved", "rejected", "revision", "null"] },
            publication_schedule: { type: "string", enum: ["weekly", "monthly", "null"] },
            notes: { type: "string" },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        EBScoreSummary: {
          type: "object",
          properties: {
            chapter_id: { type: "string" },
            series_id: { type: "string" },
            series_name: { type: "string" },
            evaluation_id: { type: "string", nullable: true },
            evaluation_status: { type: "string", enum: ["scoring", "saved", "locked"] },
            story_type: { type: "string" },
            member_stats: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  member_name: { type: "string" },
                  scores: {
                    type: "object",
                    properties: {
                      story_dialogue: { type: "number" },
                      art_design: { type: "number" },
                      panel_camera: { type: "number" },
                      pacing_climax: { type: "number" },
                      color: { type: "number" },
                    },
                  },
                  average: { type: "number" },
                  overall_comment: { type: "string" },
                  saved_at: { type: "string", format: "date-time" },
                },
              },
            },
            aggregate: {
              type: "object",
              nullable: true,
              properties: {
                scores_per_criteria: {
                  type: "object",
                  properties: {
                    story_dialogue: { type: "number" },
                    art_design: { type: "number" },
                    panel_camera: { type: "number" },
                    pacing_climax: { type: "number" },
                    color: { type: "number" },
                  },
                },
                council_average: { type: "number" },
                total_score: { type: "number" },
                label_code: { type: "string", enum: ["khong_dat", "dat", "tot", "xuat_sac"] },
                label_text: { type: "string", enum: ["Không đạt", "Đạt", "Tốt", "Xuất sắc"] },
                member_count: { type: "integer" },
              },
            },
            criteria_labels: {
              type: "object",
              additionalProperties: { type: "string" },
            },
          },
        },
        Notification: {
          type: "object",
          properties: {
            _id: { type: "string" },
            user_id: { type: "string" },
            type: { type: "string" },
            title: { type: "string" },
            message: { type: "string" },
            is_read: { type: "boolean" },
            related_entity_type: { type: "string", enum: ["series", "chapter", "page", "task", "cooperation_request", "cooperation", "te_review", "eb_evaluation", "vote"] },
            related_entity_id: { type: "string", nullable: true },
            meta: { type: "object", additionalProperties: true },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        CoinPackage: {
          type: "object",
          properties: {
            _id: { type: "string" },
            name: { type: "string" },
            description: { type: "string" },
            price_vnd: { type: "number" },
            coin_amount: { type: "integer", format: "int64", description: "Raw CoinUnit" },
            bonus_coin: { type: "integer", format: "int64", description: "Raw CoinUnit" },
            total_coin: { type: "integer", format: "int64", description: "Raw CoinUnit" },
            coin_amount_coin: { type: "string", example: "500.00" },
            coin_unit_scale: { type: "integer", example: 100 },
            sort_order: { type: "integer" },
            is_active: { type: "boolean" },
          },
        },
        Payment: {
          type: "object",
          properties: {
            _id: { type: "string" },
            user_id: { type: "string" },
            coin_package_id: { type: "string" },
            order_code: { type: "number" },
            amount_vnd: { type: "number" },
            coin_amount: { type: "integer", format: "int64", description: "Raw CoinUnit" },
            coin_amount_coin: { type: "string", example: "520.00" },
            coin_unit_scale: { type: "integer", example: 100 },
            status: { type: "string", enum: ["pending", "paid", "cancelled", "expired", "failed"] },
            description: { type: "string" },
            checkout_url: { type: "string" },
            paid_at: { type: "string", format: "date-time", nullable: true },
            createdAt: { type: "string", format: "date-time" },
          },
        },
        Wallet: {
          type: "object",
          properties: {
            _id: { type: "string" },
            user_id: { type: "string" },
            balance: { type: "integer", format: "int64", description: "Raw CoinUnit" },
            total_deposited: { type: "integer", format: "int64", description: "Raw CoinUnit" },
            total_spent: { type: "integer", format: "int64", description: "Raw CoinUnit" },
            pending_balance: { type: "integer", format: "int64", description: "Raw CoinUnit" },
            available_balance: { type: "integer", format: "int64", description: "Raw CoinUnit" },
            total_revenue: { type: "integer", format: "int64", description: "Raw CoinUnit" },
            total_withdrawn: { type: "integer", format: "int64", description: "Raw CoinUnit" },
            balance_coin: { type: "string", example: "125.50", description: "Legacy - dùng balance_coin_display" },
            pending_balance_coin: { type: "string", example: "2.40", description: "Legacy - dùng pending_balance_coin_display" },
            available_balance_coin: { type: "string", example: "1.60", description: "Legacy - dùng available_balance_coin_display" },
            // 7 field *_coin_display theo FE contract
            balance_coin_display: { type: "string", example: "125.50", description: "Display string cho balance" },
            available_balance_coin_display: { type: "string", example: "1.60", description: "Display string cho available_balance" },
            pending_balance_coin_display: { type: "string", example: "2.40", description: "Display string cho pending_balance" },
            total_revenue_coin_display: { type: "string", example: "500.00", description: "Display string cho total_revenue" },
            total_withdrawn_coin_display: { type: "string", example: "100.00", description: "Display string cho total_withdrawn" },
            total_deposited_coin_display: { type: "string", example: "200.00", description: "Display string cho total_deposited" },
            total_spent_coin_display: { type: "string", example: "75.00", description: "Display string cho total_spent" },
            current_balance: { type: "integer", format: "int64", description: "Mangaka/Assistant only: pending_balance + available_balance, raw CoinUnit" },
            current_balance_display: { type: "string", example: "4.00", description: "Mangaka/Assistant only: tổng Coin hiện có để hiển thị" },
            pending_balance_vnd: { type: "integer", example: 240, description: "Mangaka/Assistant only: VNĐ quy đổi từ pending_balance" },
            available_balance_vnd: { type: "integer", example: 160, description: "Mangaka/Assistant only: VNĐ quy đổi từ available_balance" },
            current_balance_vnd: { type: "integer", example: 400, description: "Mangaka/Assistant only: VNĐ quy đổi từ current_balance" },
            coin_unit_scale: { type: "integer", example: 100 },
            config: {
              type: "object",
              properties: {
                coin_to_vnd_rate: { type: "integer", example: 1000 },
                platform_fee_percent: { type: "number" },
                revenue_pending_hours: { type: "integer" },
              },
            },
          },
        },
        WalletTransaction: {
          type: "object",
          properties: {
            _id: { type: "string" },
            wallet_id: { type: "string" },
            user_id: { type: "string" },
            type: { type: "string", enum: ["Deposit", "Purchase", "Revenue", "Withdrawal", "Refund"] },
            direction: { type: "string", enum: ["in", "out"] },
            coin_amount: { type: "integer", format: "int64", description: "Raw CoinUnit" },
            coin_amount_coin: { type: "string", example: "5.00", description: "Legacy alias (string Coin display)" },
            coin_amount_coin_display: { type: "string", example: "5.00", description: "Canonical display string cho coin_amount" },
            coin_unit_scale: { type: "integer", example: 100 },
            vnd_amount: { type: "number" },
            description: { type: "string" },
            chapter_id: { type: "string", nullable: true },
            payment_id: { type: "string", nullable: true },
            purchased_chapter_id: { type: "string", nullable: true },
            revenue_id: { type: "string", nullable: true },
            withdrawal_id: { type: "string", nullable: true, description: "Có trên mọi transaction loại Withdrawal (debit/hoàn/complete)." },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        PurchasedChapter: {
          type: "object",
          properties: {
            _id: { type: "string" },
            reader_id: { type: "string" },
            chapter_id: { type: "string" },
            series_id: { type: "string" },
            price: { type: "integer", format: "int64", description: "Raw CoinUnit" },
            price_coin: { type: "string", example: "5.00" },
            coin_unit_scale: { type: "integer", example: 100 },
            purchased_at: { type: "string", format: "date-time" },
          },
        },
        Revenue: {
          type: "object",
          description: "Revenue share được xác định từ chapter.assistant_id, không còn lấy từ Cooperation.revenue_shares. Trường cooperation_snapshot chỉ phục vụ audit.",
          properties: {
            _id: { type: "string" },
            user_id: { type: "string" },
            user_role: { type: "string", enum: ["Mangaka", "Assistant"] },
            series_id: { type: "string" },
            chapter_id: { type: "string" },
            reader_id: { type: "string" },
            gross_coin_amount: { type: "integer", format: "int64", description: "Raw CoinUnit; purchase-level field" },
            platform_fee_coin: { type: "integer", format: "int64", description: "Raw CoinUnit; share-level field" },
            net_coin_amount: { type: "integer", format: "int64", description: "Raw CoinUnit; purchase-level field" },
            share_percentage: { type: "number", description: "100% nếu chapter không có assistant. 60% (Mangaka) hoặc 40% (Assistant) nếu có assistant." },
            coin_amount: { type: "integer", format: "int64", description: "Raw CoinUnit; share-level field" },
            gross_coin: { type: "string", example: "5.00" },
            platform_fee: { type: "string", example: "0.60" },
            net_coin: { type: "string", example: "4.00" },
            coin_amount_coin: { type: "string", example: "2.40" },
            coin_unit_scale: { type: "integer", example: 100 },
            vnd_amount: { type: "number" },
            status: { type: "string", enum: ["pending", "available", "withdrawn"] },
            available_at: { type: "string", format: "date-time" },
            available_at_processed_at: { type: "string", format: "date-time", nullable: true },
            cooperation_snapshot: {
              type: "object",
              description: "Snapshot revenue rule. source = CHAPTER_ASSISTANT (mới) | COOPERATION (cũ, deprecated).",
              properties: {
                source: { type: "string", enum: ["CHAPTER_ASSISTANT", "COOPERATION", null] },
                mangaka_id: { type: "string" },
                assistant_id: { type: "string", nullable: true },
                shares: { type: "array", items: { type: "object" } },
                platform_fee_percentage: { type: "number" },
              },
            },
            createdAt: { type: "string", format: "date-time" },
          },
        },
        Withdrawal: {
          type: "object",
          properties: {
            _id: { type: "string" },
            user_id: { type: "string" },
            user_role: { type: "string", enum: ["Mangaka", "Assistant"] },
            coin_amount: { type: "integer", format: "int64", description: "Raw CoinUnit" },
            coin_amount_coin: { type: "string", example: "250.50", description: "Legacy alias cho coin_amount_coin_display" },
            coin_amount_coin_display: { type: "string", example: "250.50", description: "Canonical display cho coin_amount" },
            coin_unit_scale: { type: "integer", example: 100 },
            coin_to_vnd_rate: { type: "integer", example: 100, description: "Snapshot VND per Coin" },
            vnd_amount: { type: "number" },
            status: { type: "string", enum: ["pending", "approved", "completed", "rejected", "cancelled"] },
            bank_snapshot: {
              type: "object",
              properties: {
                bank_name: { type: "string" },
                account_holder: { type: "string" },
                account_number: { type: "string" },
                account_number_masked: { type: "string" },
              },
            },
            note: { type: "string" },
            admin_note: { type: "string" },
            revenue_ids: {
              type: "array",
              items: { type: "string" },
              description: "Snapshot các Revenue được 'rút' bởi yêu cầu này. Có thể rỗng với dữ liệu legacy tạo trước khi field ra đời.",
            },
            refunded_at: { type: "string", format: "date-time", nullable: true },
            processed_by: { type: "string", nullable: true },
            processed_at: { type: "string", format: "date-time", nullable: true },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        FinancialSummary: {
          type: "object",
          description: "Tổng hợp nhanh toàn bộ số liệu tài chính của 1 user (chuẩn hoá v2). Các field Coin đều là raw integer CoinUnit (100 CoinUnit = 1 Coin).",
          properties: {
            current_coin: { type: "integer", format: "int64", description: "Reader: wallet.balance. Mangaka/Assistant: pending_balance + available_balance" },
            current_balance: { type: "integer", format: "int64", description: "Alias của current_coin (raw CoinUnit)" },
            pending_revenue: { type: "integer", format: "int64", description: "Mangaka/Assistant: pending_balance (raw CoinUnit). Reader = 0." },
            pending_balance: { type: "integer", format: "int64", description: "Mangaka/Assistant: alias pending_revenue (raw CoinUnit). Reader = 0." },
            available_balance: { type: "integer", format: "int64", description: "Mangaka/Assistant: available_balance (raw CoinUnit). Reader = 0." },
            total_deposit: { type: "integer", format: "int64", description: "Raw CoinUnit đã nạp (Reader = 0 cho Mangaka/Assistant)" },
            total_purchase: { type: "integer", format: "int64", description: "Raw CoinUnit đã dùng mua chapter (Reader). Mangaka/Assistant = 0." },
            total_revenue: { type: "integer", format: "int64", description: "Raw CoinUnit doanh thu tích luỹ" },
            total_withdrawal: { type: "integer", format: "int64", description: "Tổng Coin yêu cầu rút đã complete (raw CoinUnit, không tính pending/approved/rejected)" },
            total_withdrawn: { type: "integer", format: "int64", description: "Alias Wallet.total_withdrawn (raw CoinUnit)" },
            total_refund: { type: "integer", format: "int64", description: "Raw CoinUnit hoàn lại" },
          },
        },
        RevenueBySeries: {
          type: "object",
          properties: {
            series_id: { type: "string" },
            series_name: { type: "string" },
            cover_image_url: { type: "string" },
            total_coin: { type: "integer", format: "int64", description: "Raw CoinUnit" },
            total_coin_display: { type: "string", example: "250.00" },
            total_vnd: { type: "number" },
            total_gross_coin: { type: "integer", format: "int64", description: "Raw CoinUnit" },
            total_platform_fee_coin: { type: "integer", format: "int64", description: "Raw CoinUnit" },
            chapters_sold: { type: "integer", description: "Số purchase unique (đếm theo purchased_chapter_id, không nhân đôi khi 1 chapter có Assistant)" },
            by_status: {
              type: "object",
              properties: {
                pending_coin: { type: "integer", format: "int64", description: "Raw CoinUnit" },
                pending_coin_display: { type: "string", example: "10.00" },
                available_coin: { type: "integer", format: "int64", description: "Raw CoinUnit" },
                available_coin_display: { type: "string", example: "20.00" },
                withdrawn_coin: { type: "integer", format: "int64", description: "Raw CoinUnit" },
                withdrawn_coin_display: { type: "string", example: "15.00" },
              },
            },
          },
        },
        CooperationRevenueShare: {
          type: "object",
          properties: {
            cooperation_id: { type: "string" },
            mangaka: {
              type: "object",
              properties: {
                _id: { type: "string" },
                username: { type: "string" },
                full_name: { type: "string" },
              },
            },
            assistant: {
              type: "object",
              properties: {
                _id: { type: "string" },
                username: { type: "string" },
                full_name: { type: "string" },
              },
            },
            series: {
              type: "object",
              nullable: true,
              description: "null = áp dụng cho tất cả series của Mangaka",
              properties: {
                _id: { type: "string" },
                name: { type: "string" },
              },
            },
            revenue_shares: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  user_id: { type: "string" },
                  role: { type: "string", enum: ["Mangaka", "Assistant"] },
                  percentage: { type: "number" },
                },
              },
            },
            agreed_at: { type: "string", format: "date-time" },
          },
        },
        TopEarnerEntry: {
          type: "object",
          properties: {
            user_id: { type: "string" },
            username: { type: "string" },
            full_name: { type: "string" },
            avatar_url: { type: "string" },
            role: { type: "string", enum: ["Mangaka", "Assistant", "Reader"] },
            total_coin: { type: "integer", format: "int64", description: "Raw CoinUnit" },
            total_vnd: { type: "number" },
            total_gross_coin: { type: "integer", format: "int64", description: "Raw CoinUnit" },
            total_platform_fee_coin: { type: "integer", format: "int64", description: "Raw CoinUnit" },
            chapters_sold: { type: "integer" },
            withdrawn_coin: { type: "integer", format: "int64", description: "Raw CoinUnit" },
          },
        },
        TopReaderEntry: {
          type: "object",
          properties: {
            user_id: { type: "string" },
            username: { type: "string" },
            full_name: { type: "string" },
            avatar_url: { type: "string" },
            role: { type: "string", enum: ["Reader"] },
            total_coin_spent: { type: "integer", format: "int64", description: "Raw CoinUnit" },
            chapters_bought: { type: "integer" },
            chapters_purchased: { type: "integer", description: "Alias của chapters_bought (backward compat)" },
          },
        },
// Assistant Profile Stats (snake_case + camelCase backward compat)
        AssistantStats: {
          type: "object",
          description: "Stats có cả snake_case (FE contract) và camelCase (backward compat)",
          properties: {
            // Snake_case (FE contract)
            total_series: { type: "integer", description: "Số series liên quan" },
            chapters: { type: "integer", description: "Tổng số chapter đã tham gia" },
            total_tasks: { type: "integer", description: "Tổng số task được giao" },
            approved_tasks: { type: "integer", description: "Số task đã approve" },
            // CamelCase (backward compat)
            totalSeries: { type: "integer" },
            totalTasks: { type: "integer" },
            approvedTasks: { type: "integer" },
            // Earnings (raw CoinUnit)
            earnings: { type: "integer", format: "int64", description: "Raw CoinUnit" },
            earningsCoin: { type: "string", example: "125.50" },
            pendingEarnings: { type: "integer", format: "int64", description: "Raw CoinUnit" },
            pendingEarningsCoin: { type: "string", example: "2.40" },
            availableEarnings: { type: "integer", format: "int64", description: "Raw CoinUnit" },
            availableEarningsCoin: { type: "string", example: "1.60" },
            withdrawnEarnings: { type: "integer", format: "int64", description: "Raw CoinUnit" },
            withdrawnEarningsCoin: { type: "string", example: "100.00" },
            // Balance (raw CoinUnit)
            pendingBalance: { type: "integer", format: "int64", description: "Raw CoinUnit" },
            pendingBalanceCoin: { type: "string", example: "2.40" },
            availableBalance: { type: "integer", format: "int64", description: "Raw CoinUnit" },
            availableBalanceCoin: { type: "string", example: "1.60" },
            coinUnitScale: { type: "integer", example: 100 },
          },
        },
        TopSeriesEntry: {
          type: "object",
          properties: {
            series_id: { type: "string" },
            series_name: { type: "string" },
            cover_image_url: { type: "string" },
            author: {
              type: "object",
              nullable: true,
              properties: {
                _id: { type: "string" },
                username: { type: "string" },
                full_name: { type: "string" },
              },
            },
            chapters_sold: { type: "integer" },
            total_coin: { type: "integer", format: "int64", description: "Raw CoinUnit" },
            total_platform_fee_coin: { type: "integer", format: "int64", description: "Raw CoinUnit" },
            total_platform_fee_vnd: { type: "number" },
            total_gross_coin: { type: "integer", format: "int64", description: "Raw CoinUnit" },
          },
        },
        // ─── Admin Finance Schemas ───────────────────────────────────────────
        FinanceSummary: {
          type: "object",
          description: "Tổng quan tài chính hệ thống. Tất cả giá trị Coin là raw integer CoinUnit (100 CoinUnit = 1 Coin).",
          properties: {
            total_circulation_coin: { type: "integer", format: "int64", description: "Raw CoinUnit - Tổng balance+pending+available từ Wallet" },
            total_revenue_all_time_coin: { type: "integer", format: "int64", description: "Raw CoinUnit - Tổng SUM(Revenue.coin_amount)" },
            total_withdrawn_vnd: { type: "integer", description: "Raw VND - Chỉ withdrawal status=completed" },
            total_platform_coin: { type: "integer", format: "int64", description: "Raw CoinUnit - Luôn 0 (project không có system wallet)" },
            pending_withdrawals: {
              type: "object",
              properties: {
                count: { type: "integer" },
                coin: { type: "integer", format: "int64", description: "Raw CoinUnit" },
              },
            },
            total_users_with_balance: { type: "integer", description: "Số Wallet có tổng balance > 0" },
            coin_to_vnd_rate: { type: "integer" },
          },
        },
        RevenueByRole: {
          type: "object",
          description: "Phân bố tài chính theo role. Tất cả giá trị Coin là raw integer CoinUnit.",
          properties: {
            roles: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  role: { type: "string", enum: ["Admin", "Mangaka", "Assistant", "Editor", "EB", "Reader"] },
                  user_count: { type: "integer" },
                  total_earnings_coin: { type: "integer", format: "int64", description: "Raw CoinUnit" },
                  total_withdrawn_coin: { type: "integer", format: "int64", description: "Raw CoinUnit" },
                  current_balance_coin: { type: "integer", format: "int64", description: "Raw CoinUnit" },
                  pending_balance_coin: { type: "integer", format: "int64", description: "Raw CoinUnit" },
                },
              },
            },
            total_circulation_coin: { type: "integer", format: "int64", description: "Raw CoinUnit" },
          },
        },
        RevenueTimeline: {
          type: "object",
          description: "Timeline doanh thu theo ngày. Tất cả giá trị Coin là raw integer CoinUnit.",
          properties: {
            period: { type: "string", enum: ["7d", "30d", "90d", "all"] },
            points: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  date: { type: "string", format: "date", description: "Format YYYY-MM-DD" },
                  revenue_coin: { type: "integer", format: "int64", description: "Raw CoinUnit" },
                  withdrawal_coin: { type: "integer", format: "int64", description: "Raw CoinUnit" },
                  new_users: { type: "integer" },
                },
              },
            },
            summary: {
              type: "object",
              properties: {
                total_revenue_coin: { type: "integer", format: "int64", description: "Raw CoinUnit" },
                total_withdrawal_coin: { type: "integer", format: "int64", description: "Raw CoinUnit" },
                net_flow_coin: { type: "integer", format: "int64", description: "Raw CoinUnit" },
              },
            },
          },
        },
        TopEarnersEntry: {
          type: "object",
          description: "Top earner entry. Tất cả giá trị Coin là raw integer CoinUnit.",
          properties: {
            user_id: { type: "string" },
            username: { type: "string", nullable: true },
            full_name: { type: "string", nullable: true },
            avatar_url: { type: "string" },
            role: { type: "string", enum: ["Mangaka", "Assistant"] },
            total_earnings_coin: { type: "integer", format: "int64", description: "Raw CoinUnit" },
            current_balance_coin: { type: "integer", format: "int64", description: "Raw CoinUnit; pending_balance + available_balance" },
            pending_balance_coin: { type: "integer", format: "int64", description: "Raw CoinUnit" },
            total_withdrawn_coin: { type: "integer", format: "int64", description: "Raw CoinUnit - Chỉ withdrawal status=completed" },
            series_count: { type: "integer", description: "Số series duy nhất có doanh thu" },
            avg_monthly_revenue_coin: { type: "integer", format: "int64", description: "Raw CoinUnit - Làm tròn số nguyên" },
          },
        },
        WithdrawalStats: {
          type: "object",
          description: "Thống kê withdrawals theo status. Tất cả giá trị Coin là raw integer CoinUnit.",
          properties: {
            pending_count: { type: "integer" },
            pending_coin: { type: "integer", format: "int64", description: "Raw CoinUnit" },
            approved_count: { type: "integer" },
            approved_coin: { type: "integer", format: "int64", description: "Raw CoinUnit" },
            completed_count: { type: "integer" },
            completed_coin: { type: "integer", format: "int64", description: "Raw CoinUnit" },
            rejected_count: { type: "integer" },
            rejected_coin: { type: "integer", format: "int64", description: "Raw CoinUnit" },
            cancelled_count: { type: "integer" },
            cancelled_coin: { type: "integer", format: "int64", description: "Raw CoinUnit" },
          },
        },
      },
    },
    security: [{ BearerAuth: [] }],
  },
  apis: ["./routes/*.js"],
};

const swaggerSpec = swaggerJsdoc(options);
module.exports = swaggerSpec;
